-- Table: public."tbTipoOportunidade"

-- DROP TABLE public."tbTipoOportunidade";

CREATE TABLE public."tbTipoOportunidade"
(
    id_tipo_oportunidade INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    str_descricao TEXT COLLATE pg_catalog."default" NOT NULL,
    fg_status BIT(1) NOT NULL DEFAULT B'1'::"bit",
    CONSTRAINT "pk_id_tipo_oportunidade_tbTipoOportunidade" PRIMARY KEY (id_tipo_oportunidade)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbTipoOportunidade"
    OWNER to postgres;
COMMENT ON TABLE public."tbTipoOportunidade"
    IS 'O intuito dessa tabela é guardar informações dos tipos de oportunidades';
