-- Table: public."tbEmpresa"

-- DROP TABLE public."tbEmpresa";

CREATE TABLE public."tbEmpresa"
(
    id_empresa INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    str_nome TEXT COLLATE pg_catalog."default" UNIQUE NOT NULL,
    num_cnpj BIGINT UNIQUE NOT NULL,
    num_inscricao_estadual BIGINT,
    num_inscricao_municipal BIGINT,
    str_razao_social TEXT COLLATE pg_catalog."default",
    fg_status BOOLEAN NOT NULL DEFAULT 'true',
    CONSTRAINT "pk_id_empresa_tbEmpresa" PRIMARY KEY (id_empresa)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbEmpresa"
    OWNER to postgres;
COMMENT ON TABLE public."tbEmpresa"
    IS 'O intuito dessa tabela é guardar informações das empresas parceiras';
