-- Table: public."tbFiltro"

-- DROP TABLE public."tbFiltro";

CREATE TABLE public."tbFiltro"
(
    id_filtro INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_contato INTEGER NOT NULL,
    id_empresa INTEGER NULL,
    id_tipo_oportunidade INTEGER NULL,
    num_remuneracao_max NUMERIC(9,2) NOT NULL,
    num_remuneracao_min NUMERIC(9,2) NOT NULL,
    CONSTRAINT "pk_id_filtro_tbFiltro" PRIMARY KEY (id_filtro),
    CONSTRAINT "fk_id_contato_tbContato_tbFiltro" FOREIGN KEY (id_contato)
        REFERENCES public."tbContato" (id_contato) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "fk_id_empresa_tbEmpresa_tbFiltro" FOREIGN KEY (id_empresa)
        REFERENCES public."tbEmpresa" (id_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "fk_id_tipo_oportunidade_tbTipoOportunidade_tbFiltro" FOREIGN KEY (id_tipo_oportunidade)
        REFERENCES public."tbTipoOportunidade" (id_tipo_oportunidade) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT uni_tbFiltro UNIQUE (id_contato, id_empresa, id_tipo_oportunidade, num_remuneracao_max, num_remuneracao_min)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbFiltro"
    OWNER to postgres;
COMMENT ON TABLE public."tbFiltro"
    IS 'O intuito dessa tabela é guardar informações dos filtros que os contatos podem criar para disparo de aviso de novas oportunidades';
