-- Table: public."tbOportunidade"

-- DROP TABLE public."tbOportunidade";

CREATE TABLE public."tbOportunidade"
(
    id_oportunidade INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_empresa INTEGER NOT NULL,
    num_vaga SMALLINT NOT NULL,
    id_tipo_oportunidade INTEGER NOT NULL,
    num_remuneracao NUMERIC(9,2) NOT NULL,
    str_descricao TEXT COLLATE pg_catalog."default" NOT NULL,
    dat_inicio DATE NOT NULL,
    dat_fim DATE NOT NULL,
    fg_status BOOLEAN NOT NULL DEFAULT 'true',
    CONSTRAINT "pk_id_oportunidade_tbOportunidade" PRIMARY KEY (id_oportunidade),
    CONSTRAINT "fk_id_empresa_tbEmpresa_tbOportunidade" FOREIGN KEY (id_empresa)
        REFERENCES public."tbEmpresa" (id_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "fk_id_tipo_oportunidade_tbTipoOportunidade_tbOportunidade" FOREIGN KEY (id_tipo_oportunidade)
        REFERENCES public."tbTipoOportunidade" (id_tipo_oportunidade) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbOportunidade"
    OWNER to postgres;
COMMENT ON TABLE public."tbOportunidade"
    IS 'O intuito dessa tabela é guardar informações das oportunidades oferecidas pelas empresas parceiras';
