-- Table: public."tbTipoTelefone"

-- DROP TABLE public."tbTipoTelefone";

CREATE TABLE public."tbTipoTelefone"
(
    id_tipo_telefone INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    str_descricao TEXT COLLATE pg_catalog."default" NOT NULL,
    fg_status BOOLEAN NOT NULL DEFAULT 'true',
    CONSTRAINT "pk_id_tipo_telefone_tbTipoTelefone" PRIMARY KEY (id_tipo_telefone)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbTipoTelefone"
    OWNER to postgres;
COMMENT ON TABLE public."tbTipoTelefone"
    IS 'O intuito dessa tabela é guardar os tipos de telefones';
