-- Table: public."tbEmailContato"

-- DROP TABLE public."tbEmailContato";

CREATE TABLE public."tbEmailContato"
(
    id_email INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_contato INTEGER NOT NULL,
    id_tipo_email INTEGER NOT NULL,
    str_email TEXT COLLATE pg_catalog."default"  NOT NULL,
    CONSTRAINT "pk_id_email_tbEmailContato" PRIMARY KEY (id_email),
    CONSTRAINT "fk_id_contato_tbContato_tbEmailContato" FOREIGN KEY (id_contato)
        REFERENCES public."tbContato" (id_contato) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "fk_id_tipo_email_tbTipoEmail_tbEmailContato" FOREIGN KEY (id_tipo_email)
        REFERENCES public."tbTipoEmail" (id_tipo_email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbEmailContato"
    OWNER to postgres;
COMMENT ON TABLE public."tbEmailContato"
    IS 'O intuito dessa tabela é guardar os emails dos contatos';
