-- Table: public."tbEnderecoEmpresa"

-- DROP TABLE public."tbEnderecoEmpresa";

CREATE TABLE public."tbEnderecoEmpresa"
(
    id_endereco INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_empresa INTEGER NOT NULL,
    id_tipo_endereco INTEGER NOT NULL,
    num_cep INTEGER NOT NULL,
    str_logradouro TEXT COLLATE pg_catalog."default" NOT NULL,
    num_numero SMALLINT NOT NULL,
    str_bairro TEXT COLLATE pg_catalog."default" NOT NULL,
    str_cidade TEXT COLLATE pg_catalog."default" NOT NULL,
    str_uf TEXT COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "pk_id_endereco_tbEnderecoEmpresa" PRIMARY KEY (id_endereco),
    CONSTRAINT "fk_id_empresa_tbEmpresa_tbEnderecoEmpresa" FOREIGN KEY (id_empresa)
        REFERENCES public."tbEmpresa" (id_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "fk_id_tipo_endereco_tbTipoEndereco_tbEnderecoEmpresa" FOREIGN KEY (id_tipo_endereco)
        REFERENCES public."tbTipoEndereco" (id_tipo_endereco) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbEnderecoEmpresa"
    OWNER to postgres;
COMMENT ON TABLE public."tbEnderecoEmpresa"
    IS 'O intuito dessa tabela é guardar os endereços das empresas parceiras';
