-- Table: public."tbTipoEndereco"

-- DROP TABLE public."tbTipoEndereco";

CREATE TABLE public."tbTipoEndereco"
(
    id_tipo_endereco INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    str_descricao TEXT COLLATE pg_catalog."default" NOT NULL,
    fg_status BIT(1) NOT NULL DEFAULT B'1'::"bit",
    CONSTRAINT "pk_id_tipo_endereco_tbTipoEndereco" PRIMARY KEY (id_tipo_endereco)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbTipoEndereco"
    OWNER to postgres;
COMMENT ON TABLE public."tbTipoEndereco"
    IS 'O intuito dessa tabela é guardar os tipos de endereços';
