-- Table: public."tbTelefoneContato"

-- DROP TABLE public."tbTelefoneContato";

CREATE TABLE public."tbTelefoneContato"
(
    id_telefone INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_contato INTEGER NOT NULL,
    id_tipo_telefone INTEGER NOT NULL,
    num_ddd_numero SMALLINT NOT NULL,
    num_numero BIGINT NOT NULL,
    CONSTRAINT "pk_id_telefone_tbTelefoneContato" PRIMARY KEY (id_telefone),
    CONSTRAINT "fk_id_contato_tbContato_tbTelefoneContato" FOREIGN KEY (id_contato)
        REFERENCES public."tbContato" (id_contato) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "fk_id_tipo_telefone_tbTipoTelefone_tbTelefoneContato" FOREIGN KEY (id_tipo_telefone)
        REFERENCES public."tbTipoTelefone" (id_tipo_telefone) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbTelefoneContato"
    OWNER to postgres;
COMMENT ON TABLE public."tbTelefoneContato"
    IS 'O intuito dessa tabela é guardar os telefones dos contatos';
