-- Table: public."tbEmailEmpresa"

-- DROP TABLE public."tbEmailEmpresa";

CREATE TABLE public."tbEmailEmpresa"
(
    id_email INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_empresa INTEGER NOT NULL,
    id_tipo_email INTEGER NOT NULL,
    str_email TEXT COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "pk_id_email_tbEmailEmpresa" PRIMARY KEY (id_email),
    CONSTRAINT "fk_id_empresa_tbEmpresa_tbEmailEmpresa" FOREIGN KEY (id_empresa)
        REFERENCES public."tbEmpresa" (id_empresa) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "fk_id_tipo_email_tbTipoEmail_tbEmailEmpresa" FOREIGN KEY (id_tipo_email)
        REFERENCES public."tbTipoEmail" (id_tipo_email) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT uni_tbEmailEmpresa UNIQUE
        (id_empresa, str_email, id_tipo_email)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."tbEmailEmpresa"
    OWNER to postgres;
COMMENT ON TABLE public."tbEmailEmpresa"
    IS 'O intuito dessa tabela é guardar os emails das empresas parceiras';
